name: Run WB Tests

on:
  push:
    branches: [ inf-pytest ]
  pull_request:
    branches: [ inf-pytest ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
        architecture: 'x86'
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        python -m pip install -r requirements.txt
    - name: Test with pytest
      run: |
        python -m pytest
